### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by aanciaes** [LuisCor/MySQLContainerTemplate#1]
Hey devs

I tried your code and it did not work.

It gives me the following error
`zsh: command not found: docker-compose`

Do I have to install docker?
Thanks in advance

**Comment by LuisCor** [comment]
Hi, @aanciaes ,
Sorry to hear that you are having trouble running our project.
Unfortunately the information you provided is not enough for us to provide an accurate assessment.
Pleas follow the standard issue resolving guidelines and provide the following:
- Environment
- Description
- Steps to Reproduce
- Expected Behaviour
- Actual Behaviour

Best regards, the Dev Team

**Comment by aanciaes** [comment]
**Description**
Not working as expected

**Environment**
I have a grey computer with a pear (it might be an apple, im not to keen on fruit) at the back. It is currently 19ºC and I'm sitting in my living room.

**Steps to Reproduce**
To reproduce just follow your README file in my computer and you will get the bug reported.

**Expected Behaviour**
To work

**Actual Behaviour**
Doesn't work

**Comment by LuisCor** [comment]
It seems that it's your computer's fault. We advise getting rid of any computer with an apple on it. Try it on any other superior machine like a Raspberry.
